FROM node:24-alpine
WORKDIR /app
RUN corepack enable
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/api apps/api
RUN pnpm install --frozen-lockfile
CMD ["pnpm", "--filter", "@foodie/api", "migrate"]
