CREATE TABLE storefronts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  restaurant_id BIGINT UNSIGNED NOT NULL,
  headline VARCHAR(160) NOT NULL DEFAULT '',
  about VARCHAR(2000) NOT NULL DEFAULT '',
  cover_url VARCHAR(512) NULL DEFAULT NULL,
  whatsapp VARCHAR(40) NOT NULL DEFAULT '',
  instagram VARCHAR(120) NOT NULL DEFAULT '',
  published BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_storefront_restaurant (restaurant_id),
  CONSTRAINT fk_storefront_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);
