'use client';

import { money, useApp } from '../../app-context';
import { useCustomer } from '../customer-context';

export default function CarrinhoPage() {
  const { busy } = useApp();
  const { cartEntries, cartCount, subtotal, fee, estimate, meetsMinimum, cartCovered, cartRestaurantClosed, selectedAddress, selectedZone, cartBusy, cartLoaded, refreshCart, mutateCart, changeQuantity, paymentMethod, setPaymentMethod, changeFor, setChangeFor, modality, setModality, onlineCode, placing, placeOrder } = useCustomer();

  return <section className="customer-card customer-cart" id="carrinho">
    <div className="customer-card-title"><div><span className="customer-kicker">SEU PEDIDO</span><h2>Carrinho</h2></div><div className="customer-cart-heading-actions"><span>{cartCount} {cartCount === 1 ? 'item' : 'itens'}</span><button onClick={refreshCart} disabled={cartBusy || !cartLoaded}>Atualizar</button>{cartCount > 0 && <button onClick={() => mutateCart('/cart', 'DELETE', undefined, 'Carrinho esvaziado.')} disabled={cartBusy}>Esvaziar</button>}</div></div>

    {onlineCode && <section className="customer-card customer-online-payment"><div className="customer-card-title"><div><span className="customer-kicker">PAGAMENTO ONLINE</span><h2>Finalize o pagamento</h2></div></div>{onlineCode.base64 && <img className="customer-qr" src={`data:image/png;base64,${onlineCode.base64}`} alt="QR Code Pix" />}{onlineCode.text && <><label>Pix copia e cola<textarea readOnly rows={3} value={onlineCode.text} /></label><button className="customer-solid-button" type="button" onClick={() => { void navigator.clipboard?.writeText(onlineCode.text ?? ''); }}>Copiar código Pix</button></>}{onlineCode.url && <a className="customer-solid-button" href={onlineCode.url} target="_blank" rel="noreferrer">Abrir pagamento</a>}</section>}

    {cartEntries.length ? <><div className="customer-cart-items">{cartEntries.map(({ product, quantity }) => <div className="customer-cart-row" key={product.id}><div><strong>{product.name}</strong><small>{money(product.price_cents)} cada</small></div><div className="customer-quantity"><button onClick={() => changeQuantity(product.id, -1)} disabled={cartBusy} aria-label={`Remover uma unidade de ${product.name}`}>−</button><span>{quantity}</span><button onClick={() => changeQuantity(product.id, 1)} disabled={cartBusy} aria-label={`Adicionar uma unidade de ${product.name}`}>+</button></div></div>)}</div>
      <div className="customer-totals"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>Entrega</span><strong>{selectedZone ? money(fee) : '—'}</strong></div><div className="grand-total"><span>Total</span><strong>{selectedZone ? money(subtotal + fee) : '—'}</strong></div></div>
      {estimate?.distanceMeters != null && <p className="customer-muted">Entrega estimada: {(estimate.distanceMeters / 1000).toFixed(1)} km · ~{Math.max(1, Math.round((estimate.durationSeconds ?? 0) / 60))} min{estimate.feeMode === 'distance' ? ' · taxa por distância' : ''}</p>}
      {!meetsMinimum && <p className="customer-minimum">Faltam {money((selectedZone?.minimum_order_cents ?? 0) - subtotal)} para atingir o pedido mínimo desta zona.</p>}
      {!cartCovered && <p className="customer-minimum">Este restaurante não entrega no endereço selecionado. Escolha outro endereço ou esvazie o carrinho.</p>}
      {cartRestaurantClosed && <p className="customer-minimum">Este restaurante está fora do horário de funcionamento agora. Aguarde a reabertura para concluir o pedido.</p>}
      {selectedAddress && !selectedAddress.postal_code && <p className="customer-minimum">Este endereço é anterior à validação por CEP. Cadastre-o novamente para continuar.</p>}
      <div className="customer-payment"><span className="customer-kicker">PAGAMENTO</span><div className="customer-payment-methods" role="group" aria-label="Modalidade de pagamento"><button type="button" className={modality === 'on_delivery' ? 'selected' : ''} onClick={() => setModality('on_delivery')}>Na entrega</button><button type="button" className={modality === 'online' ? 'selected' : ''} onClick={() => { setModality('online'); if (paymentMethod === 'cash') setPaymentMethod('pix'); }}>Pagar agora (online)</button></div><div className="customer-payment-methods" role="group" aria-label="Forma de pagamento">{modality === 'on_delivery' && <button type="button" className={paymentMethod === 'cash' ? 'selected' : ''} onClick={() => setPaymentMethod('cash')}>Dinheiro</button>}<button type="button" className={paymentMethod === 'card' ? 'selected' : ''} onClick={() => setPaymentMethod('card')}>Cartão</button><button type="button" className={paymentMethod === 'pix' ? 'selected' : ''} onClick={() => setPaymentMethod('pix')}>Pix</button></div>{modality === 'on_delivery' && paymentMethod === 'cash' && <label className="customer-change">Troco para (opcional)<input inputMode="decimal" value={changeFor} onChange={(event) => setChangeFor(event.target.value)} placeholder="Ex.: 50,00" /></label>}{modality === 'online' && <p className="form-help">Pix: o QR aparece após confirmar. Cartão: abre a tela do provedor. Requer o Mercado Pago configurado.</p>}</div>
      <button className="customer-solid-button customer-checkout" onClick={placeOrder} disabled={busy || placing || cartBusy || !selectedAddress?.postal_code || !meetsMinimum || !cartCovered || cartRestaurantClosed}>{placing ? 'Processando...' : 'Fazer pedido'} <span>↗</span></button>
    </> : <p className="customer-muted">{cartLoaded ? 'Adicione um prato para começar. Você pode escolher vários itens do mesmo restaurante.' : 'Carregando seu carrinho...'}</p>}
  </section>;
}
