'use client';

import { useState } from 'react';
import { api, money, useApp } from '../app-context';

export default function AdminZonesPanel() {
  const { catalog, zones, postalRanges, busy, run } = useApp();
  const [restaurantId, setRestaurantId] = useState('');
  const [zoneName, setZoneName] = useState('');
  const [zoneCity, setZoneCity] = useState('Fortaleza');
  const [zoneState, setZoneState] = useState('CE');
  const [zoneFee, setZoneFee] = useState('5,99');
  const [zoneMinimum, setZoneMinimum] = useState('15,00');
  const [zoneFixed, setZoneFixed] = useState('5,99');
  const [zoneBase, setZoneBase] = useState('');
  const [zonePerKm, setZonePerKm] = useState('');
  const [zonePricingMinimum, setZonePricingMinimum] = useState('15,00');
  const [coverageZoneId, setCoverageZoneId] = useState('');
  const [postalStart, setPostalStart] = useState('');
  const [postalEnd, setPostalEnd] = useState('');
  const selectedRestaurantId = Number(restaurantId || catalog.restaurants[0]?.id || 0);
  const selectedCoverageZoneId = Number(coverageZoneId || zones[0]?.id || 0);

  return <>
    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">ÁREA DE ENTREGA</span><h2>Zonas e cobertura</h2></div><p>A taxa e o pedido mínimo pertencem à zona. Vincule cada restaurante às zonas que atende.</p></div><div className="form-grid">
      <form onSubmit={(event) => { event.preventDefault(); run(() => api('/admin/zones', { method: 'POST', body: JSON.stringify({ name: zoneName, slug: zoneName.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), city: zoneCity, state: zoneState.toUpperCase(), deliveryFeeCents: Math.round(Number(zoneFee.replace(',', '.')) * 100), minimumOrderCents: Math.round(Number(zoneMinimum.replace(',', '.')) * 100) }) }), 'Zona cadastrada.'); setZoneName(''); }}><h3>Nova zona</h3><label>Nome<input value={zoneName} onChange={(event) => setZoneName(event.target.value)} placeholder="Ex.: Fortaleza • Aldeota" required /></label><label>Cidade<input value={zoneCity} onChange={(event) => setZoneCity(event.target.value)} required /></label><label>UF<input maxLength={2} value={zoneState} onChange={(event) => setZoneState(event.target.value)} required /></label><label>Taxa em R$<input inputMode="decimal" value={zoneFee} onChange={(event) => setZoneFee(event.target.value)} required /></label><label>Pedido mínimo em R$<input inputMode="decimal" value={zoneMinimum} onChange={(event) => setZoneMinimum(event.target.value)} required /></label><button className="secondary-button" disabled={busy}>Criar zona</button></form>
      <form onSubmit={(event) => { event.preventDefault(); run(() => api('/admin/coverage', { method: 'POST', body: JSON.stringify({ restaurantId: selectedRestaurantId, zoneId: selectedCoverageZoneId }) }), 'Cobertura cadastrada.'); }}><h3>Atendimento do restaurante</h3><label>Restaurante<select value={restaurantId} onChange={(event) => setRestaurantId(event.target.value)}>{catalog.restaurants.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Zona<select value={coverageZoneId} onChange={(event) => setCoverageZoneId(event.target.value)}>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name} • {money(zone.delivery_fee_cents)}</option>)}</select></label><button className="secondary-button" disabled={busy || !selectedRestaurantId || !selectedCoverageZoneId}>Vincular zona</button><p className="form-help">Zonas cadastradas: {zones.length}. Coberturas ativas: {catalog.coverage.length}.</p></form>
      <form onSubmit={async (event) => { event.preventDefault(); const ok = await run(() => api('/admin/postal-ranges', { method: 'POST', body: JSON.stringify({ zoneId: selectedCoverageZoneId, postalStart, postalEnd }) }), 'Faixa de CEP cadastrada.'); if (ok) { setPostalStart(''); setPostalEnd(''); } }}><h3>Faixa de CEP da zona</h3><label>Zona<select value={coverageZoneId} onChange={(event) => setCoverageZoneId(event.target.value)}>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label>CEP inicial<input inputMode="numeric" placeholder="00000000" value={postalStart} onChange={(event) => setPostalStart(event.target.value.replace(/\D/g, '').slice(0, 8))} minLength={8} required /></label><label>CEP final<input inputMode="numeric" placeholder="00000999" value={postalEnd} onChange={(event) => setPostalEnd(event.target.value.replace(/\D/g, '').slice(0, 8))} minLength={8} required /></label><button className="secondary-button" disabled={busy || !selectedCoverageZoneId}>Cadastrar faixa</button><p className="form-help">Faixas não podem se sobrepor. Cadastre apenas CEPs atendidos pela zona.</p></form>
      <form onSubmit={(event) => { event.preventDefault(); const cents = (value: string) => value.trim() ? Math.round(Number(value.replace(',', '.')) * 100) : null; run(() => api(`/admin/zones/${selectedCoverageZoneId}/pricing`, { method: 'PATCH', body: JSON.stringify({ deliveryFeeCents: cents(zoneFixed) ?? 0, baseFeeCents: cents(zoneBase), perKmCents: cents(zonePerKm), minimumOrderCents: cents(zonePricingMinimum) ?? 0 }) }), 'Preços da zona atualizados.'); }}><h3>Preços da zona</h3><label>Zona<select value={coverageZoneId} onChange={(event) => setCoverageZoneId(event.target.value)}>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label>Taxa fixa em R$<input inputMode="decimal" value={zoneFixed} onChange={(event) => setZoneFixed(event.target.value)} required /></label><label>Base por distância em R$<input inputMode="decimal" value={zoneBase} onChange={(event) => setZoneBase(event.target.value)} placeholder="Opcional" /></label><label>Por km em R$<input inputMode="decimal" value={zonePerKm} onChange={(event) => setZonePerKm(event.target.value)} placeholder="Opcional" /></label><label>Pedido mínimo em R$<input inputMode="decimal" value={zonePricingMinimum} onChange={(event) => setZonePricingMinimum(event.target.value)} required /></label><button className="secondary-button" disabled={busy || !selectedCoverageZoneId}>Salvar preços</button><p className="form-help">Com “por km”, a taxa vira base + km; sem ele, mantém a taxa fixa.</p></form>
    </div></section>

    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">COBERTURA POR CEP</span><h2>Faixas cadastradas</h2></div></div>{postalRanges.length ? <div className="postal-range-list">{postalRanges.map((range) => <div key={range.id}><span><strong>{range.zone_name}</strong> · {range.postal_start} a {range.postal_end}</span><button disabled={busy} onClick={() => run(() => api(`/admin/postal-ranges/${range.id}`, { method: 'DELETE' }), 'Faixa removida.')}>Remover</button></div>)}</div> : <p className="form-help">Cadastre uma faixa para permitir novos endereços nessa zona.</p>}</section>
  </>;
}
